# Generated by Django 4.0.2 on 2022-02-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('image', models.ImageField(upload_to='materials/', verbose_name='изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='дополнительно')),
                ('is_in_stock', models.BooleanField(default=False, verbose_name='в наличии')),
                ('price', models.FloatField(verbose_name='цена')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='вес')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='длина')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='ширина')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('date_edit', models.DateField(auto_now=True, verbose_name='дата редактирования')),
                ('jew_cat', models.ForeignKey(default='Нет категории', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.category', verbose_name='категория украшения')),
                ('material_cat', models.ManyToManyField(to='core.Material', verbose_name='материал')),
                ('metal_cat', models.ManyToManyField(to='core.Metal', verbose_name='фурнитура')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.jewelry')),
            ],
        ),
    ]
